apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  # Değerler mutlaka Base64 formatında olmalıdır
  username: azhzX3VzZXI=
  password: azhzX3Bhc3N3b3Jk
  database: azhzX2Ri